---
title: "Explorando Series Temporais"
author: "Ricardo Accioly"
date: "`r Sys.Date()`"
format:
 html:
    code-link: true
---

```{r, include=FALSE}
# parametros para imagens
knitr::opts_chunk$set(
  fig.width = 8,
  fig.asp = 0.618,
  fig.retina = 3,
  dpi = 300,
  out.width = "80%"
)
```

## Carregando e visualizando dados de Produção de Cerveja

```{r}
library(fpp2)
data(ausbeer)
autoplot(ausbeer)

```

## Separando dois trechos da serie

```{r}
library(tsibble)
library(feasts)
ausbeer2 <- as_tsibble(ausbeer)
serie1 <- ausbeer2 %>% filter_index("1960 Q1" ~ "1964 Q4")
gg_season(serie1)
gg_subseries(serie1)
serie2 <- ausbeer2 %>% filter_index("2005 Q1" ~ "2009 Q4")
gg_season(serie2)
gg_subseries(serie2)
```

## Decomposição Aditiva

```{r}
library(foreign)
prodcerv <- scan("beerprod.dat")
prodcerv <- ts(prodcerv, start = 1960, freq = 4)
autoplot(prodcerv)
decompos1 <- decompose(prodcerv, type = "additive")
plot(decompos1)
decompos1

```

## Decomposição Multiplicativa

```{r}
decompos2 <- decompose(prodcerv, type = "multiplicative")
plot(decompos2)
decompos2
```
